dist: xenial
language: java
sudo: false
jdk: openjdk11
install: true
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token:
      secure: $SONAR_TOKEN
script: true
#  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=rnmartins_bookstoremanager_course
   - mvn clean verify sonar:sonar -Dsonar.projectKey=rnmartins_bookstoremanager_course
cache:
  directories:
    - $HOME/.m2
    - $home/.sonar/cache